FROM node:17-alpine

EXPOSE 3000 
RUN mkdir -p /app
WORKDIR /app

##ignore if don't have react with typescript
COPY tsconfig.json /app/tsconfig.json 

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# ENV NODE_OPTIONS=--openssl-legacy-provider
## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install

## copy all file include node modules
COPY . .

RUN npm run build

FROM nginx:1.21.4

COPY --from=0 /app/build /usr/share/nginx/html
WORKDIR /usr/share/nginx/html


CMD ["nginx","-g","daemon off;"]