FROM node:17-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

EXPOSE 3000 
RUN mkdir -p /app
WORKDIR /app

##ignore if don't have react with typescript
COPY tsconfig.json /app/tsconfig.json 

COPY package.json /app/package.json
COPY pnpm-lock.yaml /app/pnpm-lock.yaml

# ENV NODE_OPTIONS=--openssl-legacy-provider
## install only the packages defined in the pnpm-lock.yaml (faster than the normal pnpm install)
RUN pnpm install

## copy all file include node modules
COPY . .

RUN pnpm run build

FROM nginx:1.21.4

COPY --from=0 /app/build /usr/share/nginx/html
WORKDIR /usr/share/nginx/html


CMD ["nginx","-g","daemon off;"]