version: '3'

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

services:
    db:
        networks:
            - backend
    api:
        networks:
            - frontend
            - backend

    ui:
        networks:
            - frontend
        depends_on:
            - db
