version: '3'

services:
    db:
        image: postgres:14
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgdata_prod:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: mypassword

    api:
        build:
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - "3001:3001"
        depends_on:
            - db

    ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile-prod
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - "80:3000"
        environment:
            - NODE_OPTIONS=--openssl-legacy-provider

volumes:
    pgdata_prod:
        external: true
