version: '3'


services:
    db:
        image: postgres:14
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: mypassword
        
    api:
        build:
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - "3001:3001"
        

    ui:
        build:
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - "3000:3000"

volumes:
    pgdata:
        external: true
